SELECT 
    FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM 
    REST_INFO 

-- 음식종류별로 즐겨찾기수가 가장 많은 식당
WHERE (FOOD_TYPE, FAVORITES) 
    IN (
        SELECT FOOD_TYPE, MAX(FAVORITES)
        FROM REST_INFO 
        GROUP BY FOOD_TYPE
    )
ORDER BY FOOD_TYPE DESC;