-- 코드를 입력하세요
-- 2022년 10월에 작성
-- 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS	
--, B.CREATED_DATE
, TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD' ) AS CREATED_DATE

FROM USED_GOODS_BOARD A
INNER JOIN USED_GOODS_REPLY B
ON A.BOARD_ID = B.BOARD_ID

WHERE A.CREATED_DATE BETWEEN TO_DATE('2022-10-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')

ORDER BY B.CREATED_DATE, A.TITLE;